### ISSUE TITLE
launcher background overlaps with input field

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/dde-launcher#1]
( same as https://github.com/fasheng/arch-deepin/issues/147 )

![launcher](https://cloud.githubusercontent.com/assets/11800714/11615374/1e00d718-9c5f-11e5-9fa4-332228ee61d9.png)

**Comment by hualet** [comment]
@oberon2007 sorry for taking so long to respond, is the bug still there ?

**Comment by oberon2007** [comment]
Don't be sorry, @hualet ! This has been fixed a wile ago, thank you! :)

**Comment by hualet** [comment]
OK
