### ISSUE TITLE
Frequently used Apps

### ISSUE THREAD

**Issue by Grafikart** [linuxdeepin/dde-launcher#16]
dde-launcher is beautiful and I really like it but the search feature shows random apps. It would be nice to be able to sort apps using some sort of history to get frequently launched apps first. 

This is more a suggestion than an issue. So if it requires too much work, feel free to close this issue.

Thanks for your work.

**Comment by aiamuzz** [comment]
Hi,

this has been partially implmented in the latest 15.6 version ... but the same is limited to the short Window style launcher menu ... where the recent apps are listed in between the 'Search' and 'All Programs' ... 

However this is not implemented in the full screen launcher ... when can we expect a simpler recent apps category in the full screen launcher ... now that its implemented in shorter version of the launcher ?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
