### ISSUE TITLE
DDE-Launcher showing wrong software/game icons for shortcuts after the latest update

### ISSUE THREAD

**Issue by tetration** [linuxdeepin/dde-launcher#18]
As you can see in the photo I uploaded below after my DeepinOs updating to its latest version 15.4.1, some of my games lost their icons and are all using the icon of Blood(game) even when its another game such as Simcity or Retro City Rampage. Does anyone know how to fix it or this icon switch is somekind of new bug that is caused due to the new bug fixes of DDe-Launcher? 

![deepinos issue in latest update](https://user-images.githubusercontent.com/2152854/28494139-4692c80a-6efc-11e7-8c64-31e1d13e7129.png)

**Comment by tetration** [comment]
Update 2017 July 26: As you can see the glitch continues and it looks like everytime I reboot the computer it switches the icon to other ones, but they are never the right ones!
![bug continues](https://user-images.githubusercontent.com/2152854/28625509-d989f216-71f2-11e7-9a90-3eedd69c4a88.png)

**Comment by felixonmars** [comment]
I can never reproduce the problem. Are you still getting this behavior?

**Comment by tetration** [comment]
Yes, I´m still getting it.
Here Is a picture I took today. While using Deepin 15.4.1

[image: Inline image 1]

**Comment by felixonmars** [comment]
Can you try another launcher like synapse and see if the affected icons are correctly shown there?

**Comment by tetration** [comment]
@felixonmars 

I´ve just installed it and it looks like the Synapse launcher is correctly showing the icons of the softwares in my games catego unlike the DDE-launcher, which is showing the incorrect icons for each software in the game category.

_For our testing purposes I´ve used the Synapse Launcher currently Available in the Deepin Store_

I´m currently on Deepin 15.4.1 in my Desktop.

Also, I´m about to install Deepin in a laptop that I use for work and college. I´m gonna check if the same bug will occur on it. If it doesnt maybe it might be something that is glitched in my current installation?

**Comment by hualet** [comment]
Maybe that's because deepin-icon-theme sets papirus-icon-theme as the base icon theme which was flattr-icon-theme before 15.5 ?

**Comment by tetration** [comment]
Update:

Looks like the problem fixed itself after I updated System, with Deepin version 15.5 Beta Desktop

![deepinscreenshot_20171120214156](https://user-images.githubusercontent.com/2152854/33047310-3baab5ac-ce3c-11e7-8664-23e7060eaf2e.png)
