### ISSUE TITLE
Unable to open launcher

### ISSUE THREAD

**Issue by uisyudha** [linuxdeepin/dde-launcher#19]
after update of dde launcher 4.1.9-1 in arch linux unable to open the launcher, when i click the launcher button no window show up.

this is the output when i am trying to show launcher using cli command dde-launcher -s
`(dde-launcher:1833): GLib-GIO-ERROR **: Settings schema 'com.deepin.dde.launcher' does not contain a key named 'apps-icon-ratio'
Trace/breakpoint trap (core dumped)`

so, i downgrade the package to dde-launcer-4.1.8-1

**Comment by jouyouyun** [comment]
What is the version of deepin-desktop-schemas?

**Comment by felixonmars** [comment]
It should have been addressed in 3.1.17.20171013-1 and 3.1.18-1.

**Comment by uisyudha** [comment]
ok thanks, i'll close this issue
