### ISSUE TITLE
Launcher overlaps both displays

### ISSUE THREAD

**Issue by triptec** [linuxdeepin/dde-launcher#2]
I've got a dual screen setup and the launcher is centered in the middle and overlapping both screens, should it not only be on the primary display?

**Comment by fasheng** [comment]
Yes, it should be on the primary display. Do you use Deepin 2015? Which version the dde-launcher is?
>dpkg -s dde-launcher

**Comment by fasheng** [comment]
I see, it's a known issue in upstream. Thanks for your report!

**Comment by manateelazycat** [comment]
We have fixed this bug in deepin 15.2, thanks for your report!
