### ISSUE TITLE
Show in alphabetical order

### ISSUE THREAD

**Issue by redmanndotsh** [linuxdeepin/dde-launcher#20]
It's too hard to find applications on Deepin Launcher because it is shown by installation order.

**Comment by Speedhoven2** [comment]
I agree. I wish there was an option to automatically sort apps by their name. Right now the only way to do that is sorting them manually one by one, but it's time consuming and it only affects one mode at time (if you sort them in the full screen mode, the windowed mode won't be affected, and vice versa).

**Comment by DanniloSN** [comment]
I want this too

**Comment by marcussousax** [comment]
+1

**Comment by dixonge** [comment]
+1000!

**Comment by rlopess** [comment]
Please!

**Comment by gdottheking** [comment]
+1

**Comment by BLumia** [comment]
cc @wangjia12

btw, consider try type and search? it'll be much faster than finding by alphabetical order imo.

**Comment by wangjia12** [comment]
Searching may be faster if you already know what the initials are.

**Comment by nodefive** [comment]
+1000googlplex0000

This feature was available in Windows 95, back in 95!

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
