### ISSUE TITLE
after selecting all text in launcher, pressing a letter doesn't overwrite existing content

### ISSUE THREAD

**Issue by moham96** [linuxdeepin/dde-launcher#22]
Hi,
Steps to reproduce the issue:
1-Open the launcher and change the view mode to the mini menu (unity like),not the full screen mode.
2- Type any latters in the search field.
3- Press Ctrl+a to sellect all the text inside the field.
4- Press any letter and notice that the selected text is not being overwriten
Note: if after sellecting all the text you pressed a special character instead of a regular letter, then the text will be overwriten 

![deepin-screen-recorder_select area_20180216212709](https://user-images.githubusercontent.com/10559702/36336908-ac7db7a6-139d-11e8-88fa-564976ef26a8.gif)

**Comment by moham96** [comment]
@rekols  In what version is it fixed?
I'm running deepin-dock 4.6.3.2-1 and deepin-launcher 4.3.2.2-1 and the issue is still here.
Thanks

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
