### ISSUE TITLE
suggestion:use relative height for small-sized launcher instead of fixed size

### ISSUE THREAD

**Issue by linusboyle** [linuxdeepin/dde-launcher#23]
hello developer,
there're some discussions in the forum about making the launcher adjust to the monitor size. On my laptop whose height is only 768px it seems too large but for large-scale monitor it's really too small
I think a ratio about .5 is ok,but the design can vary.

best regards.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
