### ISSUE TITLE
use deepin 15.6 desktop， when i  input password to os， only show the Desktop and move mouse

### ISSUE THREAD

**Issue by LaJun** [linuxdeepin/dde-launcher#24]
click is useless ，terminal cant open by Ctrl+alt+t ，Ctrl+alt+delete also cant come to the shut page

**Comment by jouyouyun** [comment]
Distro?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
