### ISSUE TITLE
Please add build instructions + needed dependencies

### ISSUE THREAD

**Issue by DanyGee** [linuxdeepin/dde-launcher#25]
Please add build instructions + needed dependencies so we can compile it ourselves.

**Comment by felixonmars** [comment]
For now you can refer to Arch's PKGBUILD: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/deepin-launcher

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
