### ISSUE TITLE
dde-launcher doesn't close after launching DDE

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/dde-launcher#27]
After the DDE has been launched, dde-launcher doesn't close automatically. It keeps on running in the background. We have to manually stop the process from the system monitor.

Please fix it as soon as possible.

Distro: Deepin 15.7

**Comment by jouyouyun** [comment]
@haruyukilxz

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
