### ISSUE TITLE
[FEATURE] Ability to pin apps to a workspace

### ISSUE THREAD

**Issue by ubarsaiyan** [linuxdeepin/dde-launcher#29]
First of all, I would like to say I am really impressed by deepin desktop environment. It's really beautiful as well as fast.

I would like the option of pinning an app to a particular workspace so that it opens in that workspace by default, like i3wm. I thought the pin option that I see when viewing the "workspace and all open apps" screen does what I want but I can't figure out what it does. I think many users will benefit from this. Thanks.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
