### ISSUE TITLE
Deepin Launcher Does Not Consistently Show Icons

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/dde-launcher#3]
<a href="https://github.com/stevedude"><img src="https://avatars.githubusercontent.com/u/8483863?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by @stevedude**
_Wednesday Feb 24, 2016 at 14:46 GMT_
_Originally opened as https://github.com/fasheng/arch-deepin/issues/255_

----

It appears this issue was recently posted and then closed, however, I still run into issues with the Launcher being blank. If I click on the "Name" filter the icons reappear. I'm running Manjaro Deepin 15.12, 64bit with all of the latest updates.

This issue seems to be sporadic, sometimes when I click on the Launcher, the icons are there, other times, I see a blank blurred screen.

**Comment by manateelazycat** [comment]
It's a bug of manjaro, works for deepin 15.2.

Sorry, we can't reproduce this issue.
