### ISSUE TITLE
Launcher crashes frequently

### ISSUE THREAD

**Issue by rhymiz** [linuxdeepin/dde-launcher#4]
dde-launcher crashes frequently on my machine.
I have to kill the process before it becomes responsive again.
When I click on launcher or push the "Windows" button on my keyboard, it doesn't open.

**Comment by snyh** [comment]
Could you directly run the gdb dde-launcher  and paste the backtrace ?  (You need install gdb and dde-launcher-dbg)

**Comment by manateelazycat** [comment]
Haven't enough debug information for debug, close issue.

**Comment by manateelazycat** [comment]
rhymiz, please re-open this issue once you have helpful information to help us fix this problem.
