### ISSUE TITLE
Configure launcher to show in categories mode

### ISSUE THREAD

**Issue by scorninpc** [linuxdeepin/dde-launcher#42]
This is an idea for a feature, not an issue.

This launcher is great, and I like the shorter version of the launcher. When in this mode, someone wold like to configure to open always in categories mode. Its organized and clean

Thank you for this nice dev

**Comment by listenerri** [comment]
@wangjia12

**Comment by wangjia12** [comment]
thanks for your suggestion.
We will keep the previous display status and hope to make your experience better.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
