### ISSUE TITLE
[Bug] Search in russian language

### ISSUE THREAD

**Issue by n-osennij** [linuxdeepin/dde-launcher#45]
When push Win button (to open list of all apps with search bar on the top) and try to type text in english - all works fine. But if try to type text in russisn - nothing happens. You need to manually set the focus in the search field. Or start typing in English, wait for the focus to appear in the field, erase the old text, switch the language to Russian, start writing.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
