### ISSUE TITLE
Cannot launch terminal applications from launcher

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/dde-launcher#5]
I'm not sure if this is an issue of **dde-launcher** or **deepin-terminal**. 
In any case when I ttry to launch a terminal applications like for example **htop** from the launcher, nothing happens.

**Comment by fasheng** [comment]
Ehmm, For archlinux, install xterm or gnome-terminal is a temporary solution.

Maybe we could found a good solution in following releases...
@jouyouyun @hualet

**Comment by jouyouyun** [comment]
@oberon2007  any terminal emulation installed on your system, except deepin-terminal?

**Comment by oberon2007** [comment]
Ah. I see. Well I had several terminal emulators installed but neither **xterm** nor **gnome-terminal** :wink: When I have one of them installed they take over without them even being the default.
Yeah, installing gnome-terminal is ok as a workaround for now.
Of course it will be great if that can be fixed... :smile: 
What happened to the next release of deepin-terminal btw? I was expecting it months ago I think... :stuck_out_tongue_winking_eye:

**Comment by manateelazycat** [comment]
This bug has fixed in deepin-terminal 2.0 with patch: https://github.com/manateelazycat/deepin-terminal/commit/18ba6893929d1e91b9726b574c26e537f6a5d05c

After deepin 15.3 (with deepin-terminal 2.0), this bug will gone
