### ISSUE TITLE
launcher search does not compare to synapse

### ISSUE THREAD

**Issue by bksubhuti** [linuxdeepin/dde-launcher#63]
The launcher search and selection of apps while you type is not good.
I find that Synapse finds my apps much better with fewer keystrokes.

It would be good to take the synapse search code  and add it to the dde-launcher

I think it uses the zeitgeist engine to do this.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
