### ISSUE TITLE
[BUG] Chrome installed PWA Apps with wrong icon 

### ISSUE THREAD

**Issue by maxjf1** [linuxdeepin/dde-launcher#65]
Deepin supports chrome PWA apps install very well, but it always pick chrome icon instead of PWA icon. I am able to fix it manually for each PWA installed, using `Alacarte`, by changing the icon to an .png in the system.

STEPS TO REPRODUCE:
- Using chrome, access https://squoosh.app/
- Install the PWA, by clicking in the _+_ icon on the end of address bar
- close everything
- Open the Squoosh app in the launcher
- Both in the launcher and the dock, the app will open as standalone, but shoing the chrome icon, instead of the app icon.

Again, if i change the menu icon using the `Alacart` app, it works as expecteded. This also happens for chrome apps in chrome store

Fixed icons using alacarte (by default, it shows the chrome icon)
![image](https://user-images.githubusercontent.com/6114888/69563891-ba170700-0f90-11ea-961d-449038b248e7.png)

App open with fixed icon
![image](https://user-images.githubusercontent.com/6114888/69563934-cef39a80-0f90-11ea-8203-440a1ed19a92.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
