### ISSUE TITLE
Clicking on applications on Fullscreen-mode has no effect

### ISSUE THREAD

**Issue by RethyI** [linuxdeepin/dde-launcher#72]
Clicking applications doesn't start the program. Works in normal menu mode. 

Arch Linux (Endevour OS). Fresh install, newest packages.

**Comment by asdfprah** [comment]
I have the same problem with the fullscreen launcher. Also worth to note is that pressing enter the program's starts

**Comment by RethyI** [comment]
Any news on this issue?

**Comment by TheTBO** [comment]
Have the same issue on arch

**Comment by KimHono** [comment]
As far as I'm concerned, this issue seems to be addressed by the latest update of deepin-launcher 5.3.0.16-1.
I'm on Arch 5.9.1

**Comment by RethyI** [comment]
Fixed. Closing issue.
