### ISSUE TITLE
There is an artifact on the corner of compact form

### ISSUE THREAD

**Issue by gokhanyildirimlar** [linuxdeepin/dde-launcher#73]
As mentioned in the title, there is an artifact right on the corner. I have just upgraded to v1003 for testing. You can find the recorded video below.  
[DDE Launcher Artifact.zip](https://github.com/linuxdeepin/dde-launcher/files/5291705/DDE.Launcher.Artifact.zip)

Related package: dde-launcher(5.3.0.14-1)

**Comment by xmuli** [comment]
After the holiday, the test will be tested,thank
