### ISSUE TITLE
Font size and shadow text

### ISSUE THREAD

**Issue by bigbruno** [linuxdeepin/dde-launcher#8]
Why font size is static in source code and not dynamic using system configuration?

Another idea is improve shadow, because in clear wallpaper is very hard read names of applications, maybe use external css for made this simple for user personalization.

Sorry for bad english, that's not my native language.

**Comment by pangpangpang3** [comment]
It's good idea, thx for your advise, we maybe changed the design after some discuss later .

Now the app's size in launcher is depend on the  resolution, and if the font size changed, the icon size will change too. 

ps:I'm not good at English, too. Hahaha!

**Comment by sbwtw** [comment]
Fixed at new version.
